name: poincare-map
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8.6
  - pip
  # BASICS
  - numpy
  - scipy
  - pandas
  - tqdm
  # VISUALIZATION
  - matplotlib
  - xppaut
  - pip:
     - -e .  # install git checkout of demo-dsproject in editable mode
     - pynverse
     - intersect
     - git+https://github.com/markolenik/pyxpp.git
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     # - icecream
     # - jax
     # - numpyro
     # - funsor
     # - neptune-client
     # - neptune-contrib

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - black
  - mypy
  - flake8
  - pytest
  - jupyter_client==6.1.12
  - jupyter_console
  - pyright
