name: poincare-map-paper
channels:
  - conda-forge
dependencies:
  - python==3.8.6
  - pip
  # BASICS
  - numpy
  - scipy
  - pandas
  - tqdm
  - fastparquet
  # VISUALIZATION
  - matplotlib
  - xppaut
  - pip:
     - -e .  # install git checkout of project in editable mode
     - pynverse
     - intersect
     - git+https://github.com/markolenik/pyxpp.git

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - black
  - mypy
  - flake8
  - pytest
  - jupyter_client==6.1.12
  - jupyter_console
  - pyright
  - ipdb
